apiVersion: apps/v1
kind: Deployment
metadata:
  name: tekmek-order-generation-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-generation
  template:
    metadata:
      labels:
        app: order-generation
    spec:
      containers:
        - name: order-generation
          image: quazmo/tekmek-order-generation
          resources:
            limits:
              memory: 256Mi
              cpu: 1
            requests:
              memory: 256Mi
              cpu: 1
---
apiVersion: v1
kind: Service
metadata:
  name: tekmek-order-generation-clusterip-service
spec:
  selector:
    app: order-generation
  ports:
    - name: order-generation
      protocol: TCP
      port: 5250
      targetPort: 5250
