apiVersion: v1
kind: Service
metadata:
  name: tekmek-cart-service
spec:
  type: NodePort
  selector:
    app: cart
  ports:
    - name: cart
      protocol: TCP
      port: 5316
      targetPort: 5316