apiVersion: v1
kind: Service
metadata:
  name: tekmek-order-generation-service
spec:
  type: NodePort
  selector:
    app: order-generation
  ports:
    - name: order-generation
      protocol: TCP
      port: 5317
      targetPort: 5317