apiVersion: v1
kind: Service
metadata:
  name: tekmek-products-service
spec:
  type: NodePort
  selector:
    app: products
  ports:
    - name: products
      protocol: TCP
      port: 5240
      targetPort: 5240